<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Identity\Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\Financial\Modules.Financial.csproj" />
    <ProjectReference Include="..\..\Modules\Operations\Modules.Operations.csproj" />
    <ProjectReference Include="..\..\Modules\AccessControl\Modules.AccessControl.csproj" />
    <ProjectReference Include="..\..\Modules\WhatsApp\Modules.WhatsApp.csproj" />
    <ProjectReference Include="..\..\Modules\AIEngine\Modules.AIEngine.csproj" />
  </ItemGroup>

</Project>
